### ISSUE TITLE
Changing originator of sms message

### ISSUE THREAD

**Issue by ian-sayles** [messagebird/firestore-send-msg#36]
I can send sms messages from Firestore with no issues, but I can't change the originating name of the sms message, it always displays the mobile number I have configured in messagebird.
I have added an originator field to the firestore document, but it seems the extension is ignoring it.

Does the extension allow you to configure the originator of the sms?

**Comment by aodinok** [comment]
Hey @ian-sayles 

Unfortunately, there is no way to set the originator of SMS when sending messages via this extension since it uses Conversations API under the hood and is not supported there.

You can still use a direct API call to MB API without this extension: https://developers.messagebird.com/api/sms-messaging/#send-outbound-sms

That would leave you without some helpful feature like status reports and auto-send when a document is added to the collection, but it still should be possible by using nodejs SDK https://github.com/messagebird/messagebird-nodejs
